### ISSUE TITLE
Python Engine import error

### ISSUE THREAD

**Issue by KevorkSulahian** [logicalclocks/hopsworks#1191]
When I run the following line of code
`fs = project.get_feature_store()`

I am receiving the following error

ImportError                               Traceback (most recent call last)
File c:\Users\user\anaconda3\envs\ML\lib\site-packages\hsfs\engine\__init__.py:33, in init(engine_type)
     32 try:
---> 33     from hsfs.engine import python
     34 except ImportError:

File c:\Users\user\anaconda3\envs\ML\lib\site-packages\hsfs\engine\python.py:36
     35 from typing import TypeVar, Optional, Dict, Any
---> 36 from confluent_kafka import Producer
     37 from tqdm.auto import tqdm

File c:\Users\user\anaconda3\envs\ML\lib\site-packages\confluent_kafka\__init__.py:40
     20 # end delvewheel patch
     21 
     22 #!/usr/bin/env python
   (...)
     37 # limitations under the License.
     38 #
---> 40 from .deserializing_consumer import DeserializingConsumer
     41 from .serializing_producer import SerializingProducer

File c:\Users\user\anaconda3\envs\ML\lib\site-packages\confluent_kafka\deserializing_consumer.py:19
      1 #!/usr/bin/env python
      2 # -*- coding: utf-8 -*-
...
     39     )
     40 _engine_type = "python"
     41 _engine = python.Engine()

FeatureStoreException: Trying to instantiate Python as engine, but 'python' extras are missing in HSFS installation. Install with pip install hsfs[python].`]

I've tried pretty much everything I can to solve this but obviously I didn't manage to,

Windows 11 Anaconda env with python 3.8.2

**Comment by tdoehmen** [comment]
Hi, thanks for the report. It seems that this is a known issue in windows conda environments (https://github.com/ContinuumIO/anaconda-issues/issues/124759). The suggested workaround is to set the environment variable `CONDA_DLL_SEARCH_MODIFICATION_ENABLE=1` before starting the python/jupyter process. Let me know if this works for you.

**Comment by KevorkSulahian** [comment]
@tdoehmen worked like a charm!

**Comment by iocariz** [comment]
Simillar issue but I am using poetry instead of  conda.

feature_store = project.get_feature_store()

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
File [c:\Users\Pandas\AppData\Local\pypoetry\Cache\virtualenvs\src-EXz78D_B-py3.9\lib\site-packages\hsfs\engine\__init__.py:33](file:///C:/Users/Pandas/AppData/Local/pypoetry/Cache/virtualenvs/src-EXz78D_B-py3.9/lib/site-packages/hsfs/engine/__init__.py:33), in init(engine_type)
     32 try:
---> 33     from hsfs.engine import python
     34 except ImportError:

File [c:\Users\Pandas\AppData\Local\pypoetry\Cache\virtualenvs\src-EXz78D_B-py3.9\lib\site-packages\hsfs\engine\python.py:38](file:///C:/Users/Pandas/AppData/Local/pypoetry/Cache/virtualenvs/src-EXz78D_B-py3.9/lib/site-packages/hsfs/engine/python.py:38)
     37 from io import BytesIO
---> 38 from pyhive import hive
     39 from urllib.parse import urlparse

File [c:\Users\Pandas\AppData\Local\pypoetry\Cache\virtualenvs\src-EXz78D_B-py3.9\lib\site-packages\pyhive\hive.py:32](file:///C:/Users/Pandas/AppData/Local/pypoetry/Cache/virtualenvs/src-EXz78D_B-py3.9/lib/site-packages/pyhive/hive.py:32)
     31 import thrift.transport.TTransport
---> 32 import jks
     33 import os

File [c:\Users\Pandas\AppData\Local\pypoetry\Cache\virtualenvs\src-EXz78D_B-py3.9\lib\site-packages\jks\__init__.py:3](file:///C:/Users/Pandas/AppData/Local/pypoetry/Cache/virtualenvs/src-EXz78D_B-py3.9/lib/site-packages/jks/__init__.py:3)
      2 from .jks import __version__, __version_info__
----> 3 from .bks import *

File [c:\Users\Pandas\AppData\Local\pypoetry\Cache\virtualenvs\src-EXz78D_B-py3.9\lib\site-packages\jks\bks.py:6](file:///C:/Users/Pandas/AppData/Local/pypoetry/Cache/virtualenvs/src-EXz78D_B-py3.9/lib/site-packages/jks/bks.py:6)
      5 from pyasn1_modules import rfc5208, rfc2459
----> 6 from Cryptodome.Hash import HMAC, SHA
      8 from .util import *
...
     39     )
     40 _engine_type = "python"
     41 _engine = python.Engine()

FeatureStoreException: Trying to instantiate Python as engine, but 'python' extras are missing in HSFS installation. Install with `pip install hsfs[python]`.

hopworks version 3.2.0, hsfs 3.2.1 pyenv 3.9.8
