### ISSUE TITLE
exporting certificates does not work with Firefox

### ISSUE THREAD

**Issue by kai-chi** [logicalclocks/hopsworks#189]
Problem: 
1. Using Firefox go to a project in hopsworks UI, then "Settings"
2. Click "Export Certificates"
3. Only trustStore is exported. The download of keyStore is missing

It does work with Chrome.

My machine:
Ubuntu 18.10 64-bit
Firefox 66.0.2
Chrome 73.0.3683.86

**Comment by tkakantousis** [comment]
Hi @kai-chi 
It's a known issue, [HOPSWORKS-940](https://logicalclocks.atlassian.net/browse/HOPSWORKS-940). That used to work, I had a look in the angular library we use to download files from Hopsworks and didn't find something obviously wrong. It seems like a firefox changed behaviour at some point.

A workaround would be to download an archive instead of downloading both files separately. Contributions are always welcome of course :)

**Comment by kai-chi** [comment]
I'd be happy to look into that when working on the web app part of my project!
I didn't know there's a Jira for it. Closing it to avoid duplicates.
